export const GET_ALL_TRANSACTION='GET_ALL_TRANSACTION';
export const FILTER_TRANSACTION='FILTER_TRANSACTION';
export const SELECT_TRANSACTION='SELECT_TRANSACTION';
export const UPDATE_PAGINATION='UPDATE_PAGINATION';